# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21d878e1075aa0f8cc2db66c4c70c1bc88d4519ecfbcf3b8655021c93a7972b9c89896f71b8a15632d19ed0dc70ad65ab5155821f34d9e26fd86e3cf1211c4d0

test:
  secret_key_base: a0a21334c02807ea8399e91bdd12de2c400bba0947ecda3558491864293fb4efdc4d81f7c3c3c53f38402d9f460e36754274ae29d1b3bb300a9633d4080dd822

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
